export enum actionTypes {
    LOAD_ALL_TODO_START = 'LOAD_ALL_TODO_START',
    LOAD_ALL_TODO_SUCCESS = 'LOAD_ALL_TODO_SUCCESS',
    LOAD_ALL_TODO_ERROR = 'LOAD_ALL_TODO_ERROR',

    DELETE_TODO_START = 'DELETE_TODO_START',
    DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS',
    DELETE_TODO_ERROR = 'DELETE_TODO_ERROR',

    ADD_TODO_START = 'ADD_TODO_START',
    ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS',
    ADD_TODO_ERROR = 'ADD_TODO_ERROR',

    TOGGLE_TODO_START = 'TOGGLE_TODO_START',
    TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS',
    TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR',
}