export enum actionTypes {
    LOAD_ALL_TODO_START = 'LOAD_ALL_TODO_START',
    LOAD_ALL_TODO_SUCCESS = 'LOAD_ALL_TODO_SUCCESS',
    LOAD_ALL_TODO_ERROR = 'LOAD_ALL_TODO_ERROR',

    DELETE_TODO_START = 'DELETE_TODO_START',
    DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS',
    DELETE_TODO_ERROR = 'DELETE_TODO_ERROR',

}